export type LearningResourceCategory =
  | 'roadmap'
  | 'course'
  | 'book'
  | 'practice'
  | 'video'
  | 'certification'
  | 'community'
  | 'newsletter';

export type LearningResourceLevel = 'beginner' | 'intermediate' | 'advanced' | 'all';

export interface LearningResource {
  id: string;
  title: string;
  provider: string;
  category: LearningResourceCategory;
  level: LearningResourceLevel;
  url: string;
  description: string;
  tags: string[];
}

export const LEARNING_CATALOG: LearningResource[] = [
  {
    id: 'rdm-frontend',
    title: 'Frontend Developer Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/frontend',
    description: 'Step-by-step path from HTML/CSS to modern frontend architecture.',
    tags: ['frontend', 'react', 'javascript', 'css'],
  },
  {
    id: 'rdm-backend',
    title: 'Backend Developer Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/backend',
    description: 'Core backend concepts, APIs, databases, caching, and scale.',
    tags: ['backend', 'api', 'database', 'architecture'],
  },
  {
    id: 'rdm-fullstack',
    title: 'Full Stack Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/full-stack',
    description: 'Combined frontend, backend, deployment, and system design journey.',
    tags: ['fullstack', 'react', 'node', 'deploy'],
  },
  {
    id: 'rdm-devops',
    title: 'DevOps Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/devops',
    description: 'CI/CD, containers, cloud, monitoring, and SRE basics.',
    tags: ['devops', 'ci-cd', 'docker', 'kubernetes'],
  },
  {
    id: 'rdm-ml',
    title: 'AI and Data Scientist Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/ai-data-scientist',
    description: 'Statistics, modeling, ML engineering, and deployment workflows.',
    tags: ['ml', 'data-science', 'python', 'statistics'],
  },
  {
    id: 'rdm-python',
    title: 'Python Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/python',
    description: 'Language fundamentals, frameworks, tooling, and specialization tracks.',
    tags: ['python', 'backend', 'automation'],
  },
  {
    id: 'rdm-java',
    title: 'Java Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/java',
    description: 'Core Java, JVM internals, Spring ecosystem, and production practices.',
    tags: ['java', 'spring', 'backend'],
  },
  {
    id: 'rdm-react',
    title: 'React Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/react',
    description: 'React fundamentals, state patterns, routing, and performance.',
    tags: ['react', 'frontend', 'typescript'],
  },
  {
    id: 'rdm-node',
    title: 'Node.js Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/nodejs',
    description: 'Node runtime, APIs, security, and high-performance backends.',
    tags: ['nodejs', 'backend', 'javascript'],
  },
  {
    id: 'rdm-system-design',
    title: 'System Design Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/system-design',
    description: 'Build system design fundamentals for interviews and real systems.',
    tags: ['system-design', 'architecture', 'distributed-systems'],
  },
  {
    id: 'rdm-cybersecurity',
    title: 'Cyber Security Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/cyber-security',
    description: 'Security fundamentals, appsec, network security, and risk management.',
    tags: ['security', 'appsec', 'network'],
  },
  {
    id: 'rdm-product',
    title: 'Product Manager Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/product-manager',
    description: 'Product discovery, analytics, roadmap planning, and execution.',
    tags: ['product', 'analytics', 'strategy'],
  },
  {
    id: 'rdm-data-analyst',
    title: 'Data Analyst Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/data-analyst',
    description: 'SQL, BI tooling, analytics workflows, and communication skills.',
    tags: ['data', 'sql', 'tableau', 'analytics'],
  },
  {
    id: 'rdm-android',
    title: 'Android Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/android',
    description: 'Kotlin, architecture patterns, testing, and app release practices.',
    tags: ['android', 'kotlin', 'mobile'],
  },
  {
    id: 'rdm-flutter',
    title: 'Flutter Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/flutter',
    description: 'Cross-platform app development with Dart and Flutter tooling.',
    tags: ['flutter', 'mobile', 'dart'],
  },
  {
    id: 'rdm-golang',
    title: 'Go Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/golang',
    description: 'Go fundamentals, concurrency, APIs, and cloud-native backend patterns.',
    tags: ['golang', 'backend', 'concurrency'],
  },
  {
    id: 'rdm-qa',
    title: 'QA Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/qa',
    description: 'Manual testing, automation, API testing, and quality engineering.',
    tags: ['qa', 'testing', 'automation'],
  },
  {
    id: 'rdm-cloud',
    title: 'Cloud Engineer Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/aws',
    description: 'Cloud services, networking, IAM, infrastructure, and reliability.',
    tags: ['cloud', 'aws', 'infrastructure'],
  },
  {
    id: 'rdm-blockchain',
    title: 'Blockchain Roadmap',
    provider: 'roadmap.sh',
    category: 'roadmap',
    level: 'all',
    url: 'https://roadmap.sh/blockchain',
    description: 'Smart contracts, cryptography basics, and decentralized app stack.',
    tags: ['blockchain', 'web3', 'solidity'],
  },
  {
    id: 'rdm-datastructures',
    title: 'DSA Interview Roadmap',
    provider: 'InterviewReady',
    category: 'roadmap',
    level: 'all',
    url: 'https://www.interviewready.io/learn',
    description: 'Structured preparation path for coding interviews from basics to advanced.',
    tags: ['dsa', 'interview', 'algorithms'],
  },
  {
    id: 'course-cs50',
    title: 'CS50x: Introduction to Computer Science',
    provider: 'Harvard',
    category: 'course',
    level: 'beginner',
    url: 'https://cs50.harvard.edu/x/',
    description: 'Comprehensive CS foundations course with hands-on programming.',
    tags: ['cs-fundamentals', 'c', 'python', 'web'],
  },
  {
    id: 'course-ossu-cs',
    title: 'Open Source Computer Science',
    provider: 'OSSU',
    category: 'course',
    level: 'all',
    url: 'https://github.com/ossu/computer-science',
    description: 'Complete free curriculum for core CS from beginner to advanced.',
    tags: ['curriculum', 'cs', 'free'],
  },
  {
    id: 'course-fullstackopen',
    title: 'Full Stack Open',
    provider: 'University of Helsinki',
    category: 'course',
    level: 'intermediate',
    url: 'https://fullstackopen.com/en/',
    description: 'Modern full-stack web development with React, Node, GraphQL, and CI.',
    tags: ['react', 'nodejs', 'graphql', 'testing'],
  },
  {
    id: 'course-gfg-dsa',
    title: 'DSA Self-Paced',
    provider: 'GeeksforGeeks',
    category: 'course',
    level: 'intermediate',
    url: 'https://www.geeksforgeeks.org/courses/dsa-self-paced',
    description: 'Interview-focused DSA track with guided practice and contest sets.',
    tags: ['dsa', 'algorithms', 'interview'],
  },
  {
    id: 'course-google-it',
    title: 'Google IT Support Professional Certificate',
    provider: 'Google / Coursera',
    category: 'course',
    level: 'beginner',
    url: 'https://www.coursera.org/professional-certificates/google-it-support',
    description: 'IT operations and support basics for entry-level roles.',
    tags: ['it-support', 'linux', 'networking'],
  },
  {
    id: 'course-ml-specialization',
    title: 'Machine Learning Specialization',
    provider: 'DeepLearning.AI',
    category: 'course',
    level: 'intermediate',
    url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    description: 'Modern ML fundamentals with practical model building.',
    tags: ['ml', 'python', 'scikit-learn'],
  },
  {
    id: 'course-datacamp-sql',
    title: 'SQL Fundamentals',
    provider: 'DataCamp',
    category: 'course',
    level: 'beginner',
    url: 'https://www.datacamp.com/tracks/sql-fundamentals',
    description: 'Practical SQL path for analytics and backend workflows.',
    tags: ['sql', 'analytics', 'database'],
  },
  {
    id: 'course-fastapi',
    title: 'FastAPI Course',
    provider: 'freeCodeCamp',
    category: 'course',
    level: 'intermediate',
    url: 'https://www.youtube.com/watch?v=7t2alSnE2-I',
    description: 'Build production-ready APIs with FastAPI and Python.',
    tags: ['python', 'fastapi', 'api'],
  },
  {
    id: 'course-react-typescript',
    title: 'React + TypeScript Bootcamp',
    provider: 'Frontend Masters',
    category: 'course',
    level: 'intermediate',
    url: 'https://frontendmasters.com/courses/react-typescript-v2/',
    description: 'Strong typed React patterns for scalable frontend apps.',
    tags: ['react', 'typescript', 'frontend'],
  },
  {
    id: 'course-system-design',
    title: 'Grokking System Design',
    provider: 'Educative',
    category: 'course',
    level: 'advanced',
    url: 'https://www.educative.io/courses/grokking-the-system-design-interview',
    description: 'Interview-focused system design concepts and architectures.',
    tags: ['system-design', 'architecture', 'interview'],
  },
  {
    id: 'course-aws-cloud-practitioner',
    title: 'AWS Cloud Practitioner Essentials',
    provider: 'AWS Skill Builder',
    category: 'course',
    level: 'beginner',
    url: 'https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials',
    description: 'Baseline cloud literacy and AWS services overview.',
    tags: ['aws', 'cloud', 'certification'],
  },
  {
    id: 'course-kubernetes',
    title: 'Kubernetes for Developers',
    provider: 'KodeKloud',
    category: 'course',
    level: 'intermediate',
    url: 'https://kodekloud.com/courses/kubernetes-for-the-absolute-beginners-hands-on/',
    description: 'Containers orchestration and deployment lifecycle fundamentals.',
    tags: ['kubernetes', 'devops', 'containers'],
  },
  {
    id: 'course-data-eng',
    title: 'Data Engineering Zoomcamp',
    provider: 'DataTalksClub',
    category: 'course',
    level: 'intermediate',
    url: 'https://github.com/DataTalksClub/data-engineering-zoomcamp',
    description: 'End-to-end data engineering stack from ingest to analytics.',
    tags: ['data-engineering', 'etl', 'warehouse'],
  },
  {
    id: 'course-ai-agents',
    title: 'AI Agents Fundamentals',
    provider: 'DeepLearning.AI',
    category: 'course',
    level: 'intermediate',
    url: 'https://www.deeplearning.ai/short-courses/',
    description: 'Practical agent workflows and LLM application patterns.',
    tags: ['llm', 'agents', 'ai'],
  },
  {
    id: 'course-scala',
    title: 'Functional Programming in Scala',
    provider: 'EPFL',
    category: 'course',
    level: 'advanced',
    url: 'https://www.coursera.org/learn/progfun1',
    description: 'Functional programming fundamentals with strong abstractions.',
    tags: ['scala', 'fp', 'advanced'],
  },
  {
    id: 'book-clean-code',
    title: 'Clean Code',
    provider: 'Robert C. Martin',
    category: 'book',
    level: 'all',
    url: 'https://www.oreilly.com/library/view/clean-code-a/9780136083238/',
    description: 'Writing maintainable and readable code in production environments.',
    tags: ['code-quality', 'engineering-practices'],
  },
  {
    id: 'book-pragmatic-programmer',
    title: 'The Pragmatic Programmer',
    provider: 'Andrew Hunt, David Thomas',
    category: 'book',
    level: 'all',
    url: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    description: 'Practical software engineering mindset and habits.',
    tags: ['software-engineering', 'career-growth'],
  },
  {
    id: 'book-designing-data-intensive',
    title: 'Designing Data-Intensive Applications',
    provider: 'Martin Kleppmann',
    category: 'book',
    level: 'advanced',
    url: 'https://dataintensive.net/',
    description: 'Deep reference for distributed systems and modern data architecture.',
    tags: ['distributed-systems', 'database', 'architecture'],
  },
  {
    id: 'book-grokking-algorithms',
    title: 'Grokking Algorithms',
    provider: 'Aditya Bhargava',
    category: 'book',
    level: 'beginner',
    url: 'https://www.manning.com/books/grokking-algorithms',
    description: 'Visual and beginner-friendly introduction to algorithms.',
    tags: ['algorithms', 'dsa', 'interview'],
  },
  {
    id: 'book-cracking-coding-interview',
    title: 'Cracking the Coding Interview',
    provider: 'Gayle McDowell',
    category: 'book',
    level: 'intermediate',
    url: 'https://www.crackingthecodinginterview.com/',
    description: 'Interview questions, strategy, and problem-solving frameworks.',
    tags: ['interview', 'dsa', 'coding'],
  },
  {
    id: 'book-system-design-interview',
    title: 'System Design Interview',
    provider: 'Alex Xu',
    category: 'book',
    level: 'advanced',
    url: 'https://bytebytego.com/books/system-design-interview',
    description: 'System design interviews with practical architecture examples.',
    tags: ['system-design', 'interview', 'architecture'],
  },
  {
    id: 'book-you-dont-know-js',
    title: 'You Dont Know JS Yet',
    provider: 'Kyle Simpson',
    category: 'book',
    level: 'intermediate',
    url: 'https://github.com/getify/You-Dont-Know-JS',
    description: 'Deep JavaScript understanding from core language internals.',
    tags: ['javascript', 'frontend', 'backend'],
  },
  {
    id: 'book-python-crash-course',
    title: 'Python Crash Course',
    provider: 'Eric Matthes',
    category: 'book',
    level: 'beginner',
    url: 'https://nostarch.com/python-crash-course-3rd-edition',
    description: 'Hands-on Python from fundamentals to projects.',
    tags: ['python', 'beginner'],
  },
  {
    id: 'book-refactoring',
    title: 'Refactoring',
    provider: 'Martin Fowler',
    category: 'book',
    level: 'advanced',
    url: 'https://martinfowler.com/books/refactoring.html',
    description: 'Improve code structure safely through disciplined refactoring.',
    tags: ['refactoring', 'code-quality'],
  },
  {
    id: 'book-site-reliability',
    title: 'Site Reliability Engineering',
    provider: 'Google',
    category: 'book',
    level: 'advanced',
    url: 'https://sre.google/books/',
    description: 'Reliability engineering principles for large-scale systems.',
    tags: ['sre', 'devops', 'operations'],
  },
  {
    id: 'practice-leetcode',
    title: 'LeetCode Problem Sets',
    provider: 'LeetCode',
    category: 'practice',
    level: 'all',
    url: 'https://leetcode.com/problemset/',
    description: 'Coding interview problems across data structures and algorithms.',
    tags: ['dsa', 'interview', 'practice'],
  },
  {
    id: 'practice-neetcode',
    title: 'NeetCode 150',
    provider: 'NeetCode',
    category: 'practice',
    level: 'intermediate',
    url: 'https://neetcode.io/practice',
    description: 'Curated interview problem list with strong explanatory content.',
    tags: ['dsa', 'interview', 'patterns'],
  },
  {
    id: 'practice-codeforces',
    title: 'Codeforces Practice',
    provider: 'Codeforces',
    category: 'practice',
    level: 'advanced',
    url: 'https://codeforces.com/problemset',
    description: 'Competitive programming for speed and problem-solving depth.',
    tags: ['competitive-programming', 'dsa'],
  },
  {
    id: 'practice-gfg',
    title: 'GeeksforGeeks Practice',
    provider: 'GeeksforGeeks',
    category: 'practice',
    level: 'all',
    url: 'https://practice.geeksforgeeks.org/',
    description: 'Topic-wise coding and interview practice tracks.',
    tags: ['dsa', 'interview', 'practice'],
  },
  {
    id: 'practice-hackerrank',
    title: 'HackerRank Interview Prep',
    provider: 'HackerRank',
    category: 'practice',
    level: 'beginner',
    url: 'https://www.hackerrank.com/interview/interview-preparation-kit',
    description: 'Structured problem tracks and company-style coding challenges.',
    tags: ['coding', 'practice', 'interview'],
  },
  {
    id: 'practice-sqlzoo',
    title: 'SQLZoo',
    provider: 'SQLZoo',
    category: 'practice',
    level: 'beginner',
    url: 'https://sqlzoo.net/',
    description: 'Interactive SQL practice from basics to joins and aggregation.',
    tags: ['sql', 'database', 'practice'],
  },
  {
    id: 'practice-exercism',
    title: 'Exercism',
    provider: 'Exercism',
    category: 'practice',
    level: 'all',
    url: 'https://exercism.org/',
    description: 'Mentored coding exercises across many programming languages.',
    tags: ['practice', 'languages', 'mentorship'],
  },
  {
    id: 'practice-kaggle',
    title: 'Kaggle Learn and Competitions',
    provider: 'Kaggle',
    category: 'practice',
    level: 'intermediate',
    url: 'https://www.kaggle.com/learn',
    description: 'Applied data science and ML practice with real datasets.',
    tags: ['ml', 'data-science', 'practice'],
  },
  {
    id: 'video-freecodecamp',
    title: 'freeCodeCamp Long-form Tutorials',
    provider: 'YouTube',
    category: 'video',
    level: 'all',
    url: 'https://www.youtube.com/@freecodecamp',
    description: 'Project-based tutorials covering full stack and data tracks.',
    tags: ['video', 'fullstack', 'python', 'javascript'],
  },
  {
    id: 'video-traversymedia',
    title: 'Traversy Media',
    provider: 'YouTube',
    category: 'video',
    level: 'beginner',
    url: 'https://www.youtube.com/@TraversyMedia',
    description: 'Developer crash courses for frontend and backend technologies.',
    tags: ['video', 'frontend', 'backend'],
  },
  {
    id: 'video-techworldwithnana',
    title: 'TechWorld with Nana',
    provider: 'YouTube',
    category: 'video',
    level: 'intermediate',
    url: 'https://www.youtube.com/@TechWorldwithNana',
    description: 'Practical DevOps and cloud engineering education.',
    tags: ['devops', 'cloud', 'kubernetes'],
  },
  {
    id: 'video-gaurav-sen',
    title: 'System Design by Gaurav Sen',
    provider: 'YouTube',
    category: 'video',
    level: 'intermediate',
    url: 'https://www.youtube.com/@gkcs',
    description: 'System design breakdowns and interview-oriented architecture discussions.',
    tags: ['system-design', 'interview'],
  },
  {
    id: 'video-striver',
    title: 'Striver DSA and SDE Sheet',
    provider: 'TakeUForward',
    category: 'video',
    level: 'intermediate',
    url: 'https://www.youtube.com/c/takeUforward',
    description: 'Structured DSA and interview preparation tutorials.',
    tags: ['dsa', 'interview', 'video'],
  },
  {
    id: 'video-sentdex',
    title: 'Sentdex Python and ML',
    provider: 'YouTube',
    category: 'video',
    level: 'intermediate',
    url: 'https://www.youtube.com/@sentdex',
    description: 'Python automation, ML workflows, and developer tooling videos.',
    tags: ['python', 'ml', 'video'],
  },
  {
    id: 'cert-aws-ccp',
    title: 'AWS Certified Cloud Practitioner',
    provider: 'AWS',
    category: 'certification',
    level: 'beginner',
    url: 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
    description: 'Entry-level cloud certification recognized by recruiters.',
    tags: ['aws', 'cloud', 'certification'],
  },
  {
    id: 'cert-azure-fundamentals',
    title: 'Microsoft Azure Fundamentals (AZ-900)',
    provider: 'Microsoft',
    category: 'certification',
    level: 'beginner',
    url: 'https://learn.microsoft.com/credentials/certifications/azure-fundamentals/',
    description: 'Fundamental cloud and Azure platform certification.',
    tags: ['azure', 'cloud', 'certification'],
  },
  {
    id: 'cert-gcp-digital',
    title: 'Google Cloud Digital Leader',
    provider: 'Google Cloud',
    category: 'certification',
    level: 'beginner',
    url: 'https://cloud.google.com/certification/cloud-digital-leader',
    description: 'Cloud business and platform fundamentals for GCP.',
    tags: ['gcp', 'cloud', 'certification'],
  },
  {
    id: 'cert-kubernetes-cka',
    title: 'Certified Kubernetes Administrator',
    provider: 'Linux Foundation',
    category: 'certification',
    level: 'advanced',
    url: 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/',
    description: 'Hands-on Kubernetes operations and cluster management certification.',
    tags: ['kubernetes', 'devops', 'certification'],
  },
  {
    id: 'cert-terraform',
    title: 'HashiCorp Terraform Associate',
    provider: 'HashiCorp',
    category: 'certification',
    level: 'intermediate',
    url: 'https://www.hashicorp.com/certification/terraform-associate',
    description: 'Infrastructure as code skills validated for DevOps pipelines.',
    tags: ['terraform', 'devops', 'infrastructure'],
  },
  {
    id: 'cert-security-plus',
    title: 'CompTIA Security+',
    provider: 'CompTIA',
    category: 'certification',
    level: 'intermediate',
    url: 'https://www.comptia.org/certifications/security',
    description: 'Security baseline certification for security-focused career tracks.',
    tags: ['security', 'certification'],
  },
  {
    id: 'community-github',
    title: 'GitHub Open Source',
    provider: 'GitHub',
    category: 'community',
    level: 'all',
    url: 'https://github.com/explore',
    description: 'Contribute to public repositories and build a visible developer profile.',
    tags: ['open-source', 'community', 'portfolio'],
  },
  {
    id: 'community-devto',
    title: 'DEV Community',
    provider: 'DEV.to',
    category: 'community',
    level: 'all',
    url: 'https://dev.to/',
    description: 'Developer discussions, tutorials, and networking with engineers.',
    tags: ['community', 'networking'],
  },
  {
    id: 'community-reddit-cscareer',
    title: 'CS Career Questions',
    provider: 'Reddit',
    category: 'community',
    level: 'all',
    url: 'https://www.reddit.com/r/cscareerquestions/',
    description: 'Career discussions around interviews, offers, and skill growth.',
    tags: ['career', 'community', 'interview'],
  },
  {
    id: 'community-hn',
    title: 'Hacker News',
    provider: 'Y Combinator',
    category: 'community',
    level: 'all',
    url: 'https://news.ycombinator.com/',
    description: 'Tech news and long-form discussion for industry awareness.',
    tags: ['news', 'community', 'industry'],
  },
  {
    id: 'community-discord-coding',
    title: 'The Coding Den',
    provider: 'Discord',
    category: 'community',
    level: 'all',
    url: 'https://discord.com/invite/code',
    description: 'Peer support, study groups, and interview prep discussions.',
    tags: ['discord', 'community', 'mentorship'],
  },
  {
    id: 'newsletter-pointer',
    title: 'Pointer',
    provider: 'Pointer.io',
    category: 'newsletter',
    level: 'all',
    url: 'https://www.pointer.io/',
    description: 'Weekly software engineering articles curated for working developers.',
    tags: ['newsletter', 'engineering'],
  },
  {
    id: 'newsletter-bytebytego',
    title: 'ByteByteGo Newsletter',
    provider: 'ByteByteGo',
    category: 'newsletter',
    level: 'all',
    url: 'https://blog.bytebytego.com/',
    description: 'System design concepts and architecture best practices.',
    tags: ['system-design', 'newsletter'],
  },
  {
    id: 'newsletter-mlops',
    title: 'MLOps Community Newsletter',
    provider: 'MLOps Community',
    category: 'newsletter',
    level: 'intermediate',
    url: 'https://mlops.community/',
    description: 'Production ML and ML platform engineering insights.',
    tags: ['mlops', 'ml', 'newsletter'],
  },
  {
    id: 'newsletter-lastweekinaws',
    title: 'Last Week in AWS',
    provider: 'Corey Quinn',
    category: 'newsletter',
    level: 'all',
    url: 'https://www.lastweekinaws.com/',
    description: 'Cloud updates and practical commentary on AWS ecosystem changes.',
    tags: ['aws', 'cloud', 'newsletter'],
  },
  {
    id: 'newsletter-javascriptweekly',
    title: 'JavaScript Weekly',
    provider: 'Cooperpress',
    category: 'newsletter',
    level: 'all',
    url: 'https://javascriptweekly.com/',
    description: 'Curated JavaScript and frontend ecosystem updates every week.',
    tags: ['javascript', 'frontend', 'newsletter'],
  },
  {
    id: 'newsletter-pythonweekly',
    title: 'Python Weekly',
    provider: 'Python Weekly',
    category: 'newsletter',
    level: 'all',
    url: 'https://www.pythonweekly.com/',
    description: 'Python ecosystem updates, guides, and project highlights.',
    tags: ['python', 'newsletter'],
  },
];

